
# tap repositories and their packages

tap homebrew/core
brew ack
brew adns
brew ant
brew aom
brew autoconf
brew automake
brew awscli
brew bower
brew cairo
brew cask
brew ccat
brew clang-format
brew cmake
brew coreutils
brew cscope
brew ctags
brew docker
brew docker-machine
brew emacs
brew ffmpeg
brew figlet
brew fish
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fswatch
brew fzf
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghi
brew giflib
brew git
brew glib
brew gmp
brew gnu-sed
brew gnupg
brew gnutls
brew go
brew gradle
brew graphite2
brew graphviz
brew harfbuzz
brew hidapi
brew htop
brew httpie
brew hub
brew icu4c
brew imagemagick
brew jpeg
brew jq
brew lame
brew leptonica
brew libass
brew libassuan
brew libbluray
brew libcroco
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libogg
brew libpng
brew librsvg
brew libsamplerate
brew libsndfile
brew libsoxr
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvorbis
brew libvpx
brew libyaml
brew libzip
brew little-cms2
brew lnav
brew lua
brew luajit
brew m-cli
brew mackup
brew mas
brew maven
brew mitmproxy
brew mongodb
brew mtr
brew ncurses
brew nettle
brew nginx
brew node
brew npth
brew nvm
brew oniguruma
brew opencore-amr
brew openjpeg
brew openssl
brew opus
brew p11-kit
brew p7zip
brew pandoc
brew pango
brew pcre
brew pcre2
brew perl
brew pinentry
brew pixman
brew pkg-config
brew platformio
brew protobuf
brew pv
brew pwgen
brew pyenv
brew python
brew python@2
brew qt
brew readline
brew reattach-to-user-namespace
brew redis
brew rsync
brew rtmpdump
brew rubberband
brew ruby
brew screenfetch
brew sdl2
brew shfmt
brew slimerjs
brew snappy
brew speex
brew sqlite
brew ssh-copy-id
brew tag
brew telnet
brew tesseract
brew testssl
brew the_silver_searcher
brew thefuck
brew theora
brew tldr
brew tmux
brew todo-txt
brew tree
brew uncrustify
brew unison
brew unrar
brew vim
brew watch
brew watchexec
brew watchman
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew yarn
brew youtube-dl
brew zsh
brew zsh-autosuggestions
brew zsh-syntax-highlighting

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-fira-code
cask font-hack-nerd-font

tap homebrew/cask-versions
cask brave-browser-dev
cask firefox-developer-edition

tap homebrew/services

tap homebrew/cask
cask 1password
cask alfred
cask android-platform-tools
cask android-studio
cask bartender
cask bitbar
cask cheatsheet
cask docker-toolbox
cask firefox
cask fork
cask gimp
cask graphql-playground
cask kap
cask keyboard-maestro
cask launchrocket
cask marta
cask openscad
cask postman
cask react-native-debugger
cask shiftit
cask spotify
cask steam
cask tigervnc-viewer
cask virtualbox
cask vivaldi
cask vnc-viewer

tap candid82/brew
brew joker

tap caskroom/fonts
cask font-firacode-nerd-font

tap caskroom/fonts

tap getantibody/tap
brew antibody

tap git-chglog/git-chglog

tap moul/moul
brew docker-diff

tap rcmdnk/file
brew brew-file

tap yqrashawn/goku

# Other Homebrew packages
brew chromedriver

# Other Cask applications
cask 1password-cli
cask android-file-transfer
cask android-ndk
cask android-sdk
cask arduino
cask bettertouchtool
cask boostnote
cask divvy
cask dropbox
cask entonnoir
cask etcher
cask franz
cask google-chrome
cask hma-pro-vpn
cask java8
cask karabiner-elements
cask launchcontrol
cask macdown
cask nvalt
cask opera
cask pycharm
cask rdm
cask robo-3t
cask sourcetree
cask squidman
cask textmate
cask totalspaces
cask visual-studio-code
cask vlc

# App Store applications
appstore 937984704 Amphetamine (4.0.4)
appstore 1081413713 GIF Brewery 3 (3.9.1)
appstore 408981434 iMovie (10.1.9)
appstore 0 Install macOS Mojave (14.0.22)
appstore 526298438 Lightshot Screenshot (2.18)
appstore 414030210 LimeChat (2.43)
appstore 823766827 OneDrive (18.151.0729)
appstore 880001334 Reeder (3.2.1)
appstore 803453959 Slack (3.3.2)
appstore 497799835 Xcode_10 (10.0)
